'use client';
import Image from 'next/image';
import clsx from 'clsx';
import { Message } from '@/types';
import { useAppDispatch } from '@/store/hooks';
import { respondToInvite } from '@/store/slices/messageSlice';
export default function MessageBubble({ message }: { message: Message }) {
  const dispatch = useAppDispatch(); const isMine = message.sender === 'me';
  if (message.kind === 'trip-invite' && message.invite) { const { invite } = message; return <div className={clsx('flex flex-col gap-1', isMine ? 'items-end' : 'items-start')}><div className="w-64 overflow-hidden rounded-2xl bg-white shadow-soft"><div className="relative h-28 w-full"><Image src={invite.imageUrl} alt={invite.title} fill sizes="256px" className="object-cover" /></div><div className="p-3"><p className="text-sm font-semibold text-ink">{invite.title}</p><p className="mt-1 text-xs text-ink-soft">📅 {invite.date} · 🕐 {invite.time}</p>{invite.responded ? <p className={clsx('mt-2 text-xs font-semibold', invite.responded === 'accepted' ? 'text-emerald-600' : 'text-red-500')}>{invite.responded === 'accepted' ? 'You accepted this trip' : 'You declined this trip'}</p> : <div className="mt-2 flex gap-2"><button type="button" onClick={() => dispatch(respondToInvite({ messageId: message.id, response: 'rejected' }))} className="focus-ring flex-1 rounded-full bg-surface-muted py-1.5 text-xs font-semibold text-ink-soft">Reject</button><button type="button" onClick={() => dispatch(respondToInvite({ messageId: message.id, response: 'accepted' }))} className="focus-ring flex-1 rounded-full bg-accent py-1.5 text-xs font-semibold text-white">Accept</button></div>}</div></div><span className="px-1 text-[11px] text-ink-soft">{message.timestamp}</span></div>; }
  const media = message.kind === 'image' && message.mediaUrl ? <Image src={message.mediaUrl} alt={message.fileName || 'Shared image'} width={280} height={220} className="max-h-56 w-auto rounded-xl object-cover" /> : message.kind === 'video' && message.mediaUrl ? <video controls className="max-h-56 max-w-[280px] rounded-xl" src={message.mediaUrl} /> : message.kind === 'location' && message.latitude !== undefined && message.longitude !== undefined ? <a href={`https://www.google.com/maps?q=${message.latitude},${message.longitude}`} target="_blank" rel="noreferrer" className="block rounded-xl bg-white/20 px-3 py-2 underline">📍 Open shared location</a> : null;
  return <div className={clsx('flex flex-col gap-1', isMine ? 'items-end' : 'items-start')}><div className={clsx('max-w-[80%] rounded-2xl px-4 py-2 text-sm', isMine ? 'rounded-br-sm bg-accent text-white' : 'rounded-bl-sm bg-surface-muted text-ink')}>{media}{message.text && <p className={media ? 'mt-2' : ''}>{message.text}</p>}</div><span className="px-1 text-[11px] text-ink-soft">{message.timestamp}</span></div>;
}
